// <auto-generated />
namespace Obras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_ve1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_ve1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803100552508_db_ve1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
